server {
    listen 80;
    server_name cctv.smk.local;

    root /home/ardo/custom-cctv;
    index index.html;

    # Dashboard static files
    location / {
        try_files $uri $uri/ =404;
    }

    # Dashboard subdirectory
    location /dashboard/ {
        alias /home/ardo/custom-cctv/dashboard/;
        try_files $uri $uri/index.html =404;
    }
}
